export const CUSS_WORDS = [
  "FUCK",
  "SHIT",
  "PISS",
  "CUNT",
  "DICK",
  "JIZZ",
  "TITS",
  "COCK",
  "DONG",
  "TWAT",
  "FART",
  "POOP",
  "NIPS",
  "CRAP",
  "HELL",
  "THOT",
  "DAMN",
  "SIMP",
  "ARSE",
  "KNOB",
  "CUCK",
  "SLUT",
  "WANK",
  "NUTS",
  "BUTT",
  "SHAG",
  "GASH",
  "JUGS",
  "MUFF",
  "BANG",
  "DIKE",
  "SLIT",
  "DUMP",
  "CLIT",
  "HUMP",
  "TURD",
  "ANAL",
  "FROT",
  "GIMP",
  "PIMP",
  "BOOB",
  "ANUS",
  "BUSH",
  "PORN",
  "CLAM",
  "MILF",
  "BDSM",
  "SEXT",
  "WOOD",
];

export const CUSS_WORDS_JAN = [
  {
    word: "FUCK",
    pronounce: "/fək/",
    type: "VULGAR SLANG",
    def: "have sex with (someone).",
    def2: "ruin or damage (something).",
    example: "Oh God YES! Fuck me! Fuck me harder!",
  },
  {
    word: "SHIT",
    pronounce: "/SHit/",
    type: "VULGAR SLANG",
    def: "feces.",
    def2: "a contemptible or worthless person.",
    example: "Eat shit... you stupid piece of shit.",
  },
  {
    word: "PISS",
    pronounce: "/pis/",
    type: "VULGAR SLANG",
    def: "urinate.",
    def2: "(none)",
    example: "Bro! Wtf? Don't piss on my cat!",
  },
  {
    word: "CUNT",
    pronounce: "/kənt/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "a contemptible or worthless person.",
    example: "... and that's when I kicked her right in the cunt.",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "TITS",
    pronounce: "/tits/ ",
    type: "VULGAR SLANG",
    def: "a woman's breasts or nipples.",
    def2: "(none)",
    example: "Excuse me mam, may I please play with your tits?",
  },
  {
    word: "COCK",
    pronounce: "/käk/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Nice cock, bro.",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "FART",
    pronounce: "/färt/",
    type: "INFORMAL",
    def: "emit gas from the anus.",
    def2: "waste time on silly or trivial things.",
    example: "Dude... did you just fart?",
  },
  {
    word: "POOP",
    pronounce: "/po͞op/",
    type: "INFORMAL",
    def: "excrement.",
    def2: "defecate.",
    example: "Don't go in there bro, someone smeard poop all over the stall.",
  },
  {
    word: "NIPS",
    pronounce: "/nips/",
    type: "INFORMAL",
    def: "a man's or woman's nipples.",
    def2: "(none)",
    example: "It's so cold in here my nips could cut glass.",
  },
  {
    word: "CRAP",
    pronounce: "/krap/",
    type: "VULGAR SLANG",
    def: "something of extremely poor quality.",
    def2: "excrement.",
    example: "This pasta tastes like crap.",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SIMP",
    pronounce: "/simp/",
    type: "DEROGATORY•INFORMAL",
    def: "a man that is too attentive and submissive to women",
    def2: "(none)",
    example:
      "Yeah, he totally simps for me. He watches my dog while I fuck his friend.",
  },
  {
    word: "ARSE",
    pronounce: "/ärs/",
    type: "VULGAR SLANG•BRITISH",
    def: "a person's buttocks or anus.",
    def2: "a stupid, irritating, or contemptible person.",
    example: "He's a pain in the arse, but he can really build a shed!",
  },
  {
    word: "WANK",
    pronounce: "/waNGk/",
    type: "VULGAR SLANG•BRITISH",
    def: "masturbate.",
    def2: "(none)",
    example: "Now if you'll all excuse me, I'm off to have a nice wank.",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },

  {
    word: "BUTT",
    pronounce: "/bət/",
    type: "COLLOQUIAL",
    def: "the buttocks or anus.",
    def2: "(anus)",
    example: "If you're good tonight, I'll let you put it in my butt.",
  },
  {
    word: "SHAG",
    pronounce: "/SHaɡ/",
    type: "VULGAR SLANG•BRITISH",
    def: "have sex with (someone).",
    def2: "an act of having sex.",
    example: "Shall we shag now? Or shag later?",
  },
  {
    word: "GASH",
    pronounce: "/ɡaSH/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example:
      "She's got a gash like the mariana trench, but she always lets me touch it!",
  },
  {
    word: "JUGS",
    pronounce: "/jəɡs/",
    type: "VULGAR SLANG",
    def: "a woman's breasts.",
    def2: "(none)",
    example: "Damn son, look at those jugs.",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "BANG",
    pronounce: "/baNG/",
    type: "VULGAR SLANG",
    def: "an act or instance of having sex.",
    def2: "(none)",
    example: "Let's go bang in the back of my Honda, baby.",
  },
  {
    word: "DIKE",
    pronounce: "/dīk/",
    type: "OFFENSIVE",
    def: "a lesbian.",
    def2: "(none)",
    example: "Bro, she must be a dike, she won't even let me get her number.",
  },
];

export const CUSS_WORDS_FEB = [
  {
    word: "SLIT",
    pronounce: "/slit/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example: "Nice slit, baby.",
  },
  {
    word: "DUMP",
    pronounce: "/dəmp/",
    type: "VULGAR SLANG",
    def: "an act of defecation.",
    def2: "(none)",
    example:
      "Bro, this cheesy gordida crunch is making me have to take a huge dump.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "TURD",
    pronounce: "/tərd/",
    type: "VULGAR SLANG",
    def: "a lump of excrement.",
    def2: "a person regarded as obnoxious or contemptible.",
    example:
      "There's a turd on the floor Josh, why the fuck is there a turd on the floor!?",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FROT",
    pronounce: "/fɹɒt/",
    type: "VULGAR SLANG",
    def: "A sexual act in which two males rub each other's penises",
    def2: "(none)",
    example: "Hey bro... want to frot?",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "BUSH",
    pronounce: "/bo͝oSH/",
    type: "VULGAR SLANG",
    def: "a woman's pubic hair.",
    def2: "(none)",
    example: "A dick in the ass is worth two in the bush.",
  },
  {
    word: "PORN",
    pronounce: "/pôrn/",
    type: "INFORMAL",
    def: "pornography.",
    def2: "pornographic.",
    example:
      "I like my tacos with cilantro and porn - shit! Corn, I mean corn...",
  },
  {
    word: "CLAM",
    pronounce: "/klam/",
    type: "VULGAR SLANG",
    def: "the female external genitals; the vulva, the vagina.",
    def2: "(none)",
    example:
      "Let's just say, he left me with a pearl in my clam. (girls don't ever say this)",
  },
  {
    word: "MILF",
    pronounce: "/ˈmilf/",
    type: "INFORMAL",
    def: "a sexually attractive older woman, typically one who has children.",
    def2: "mother I'd like to fuck.",
    example: "I don't care how old she is, that bitch is a MILF",
  },
  {
    word: "BDSM",
    pronounce: "as is",
    type: "INFORMAL",
    def: "A physical, psychological and usually sexual power-role-play with consensual participants.",
    def2: "bondage, domination, submission, masochism.",
    example: "(That one Rihanna song)",
  },
  {
    word: "SEXT",
    pronounce: "/sekst/",
    type: "INFORMAL",
    def: "send (someone) sexually explicit photographs or messages via mobile phone.",
    def2: "(none)",
    example: "Sexting, it's not sex it's the next best thing.",
  },
  {
    word: "WOOD",
    pronounce: "/wo͝od/",
    type: "VULGAR SLANG•US",
    def: "have an erection",
    def2: "(none)",
    example: "I woke up with wood, man. Like I was pitching a tent.",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "COCK",
    pronounce: "/käk/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Nice cock, bro.",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "BUSH",
    pronounce: "/bo͝oSH/",
    type: "VULGAR SLANG",
    def: "a woman's pubic hair.",
    def2: "(none)",
    example: "A dick in the ass is worth two in the bush.",
  },
  {
    word: "CRAP",
    pronounce: "/krap/",
    type: "VULGAR SLANG",
    def: "something of extremely poor quality.",
    def2: "excrement.",
    example: "This pasta tastes like crap.",
  },
];

export const CUSS_WORDS_MARCH = [
  {
    word: "PORN",
    pronounce: "/pôrn/",
    type: "INFORMAL",
    def: "pornography.",
    def2: "pornographic.",
    example:
      "I like my tacos with cilantro and porn - shit! Corn, I mean corn...",
  },
  {
    word: "JUGS",
    pronounce: "/jəɡs/",
    type: "VULGAR SLANG",
    def: "a woman's breasts.",
    def2: "(none)",
    example: "Damn son, look at those jugs.",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FUCK",
    pronounce: "/fək/",
    type: "VULGAR SLANG",
    def: "have sex with (someone).",
    def2: "ruin or damage (something).",
    example: "Oh God YES! Fuck me! Fuck me harder!",
  },
  {
    word: "FART",
    pronounce: "/färt/",
    type: "INFORMAL",
    def: "emit gas from the anus.",
    def2: "waste time on silly or trivial things.",
    example: "Dude... did you just fart?",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "SLIT",
    pronounce: "/slit/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example: "Nice slit, baby.",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "TITS",
    pronounce: "/tits/ ",
    type: "VULGAR SLANG",
    def: "a woman's breasts or nipples.",
    def2: "(none)",
    example: "Excuse me mam, may I please play with your tits?",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "ARSE",
    pronounce: "/ärs/",
    type: "VULGAR SLANG•BRITISH",
    def: "a person's buttocks or anus.",
    def2: "a stupid, irritating, or contemptible person.",
    example: "He's a pain in the arse, but he can really build a shed!",
  },
  {
    word: "PISS",
    pronounce: "/pis/",
    type: "VULGAR SLANG",
    def: "urinate.",
    def2: "(none)",
    example: "Bro! Wtf? Don't piss on my cat!",
  },
  {
    word: "CLAM",
    pronounce: "/klam/",
    type: "VULGAR SLANG",
    def: "the female external genitals; the vulva, the vagina.",
    def2: "(none)",
    example:
      "Let's just say, he left me with a pearl in my clam. (girls don't ever say this)",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "MILF",
    pronounce: "/ˈmilf/",
    type: "INFORMAL",
    def: "a sexually attractive older woman, typically one who has children.",
    def2: "mother I'd like to fuck.",
    example: "I don't care how old she is, that bitch is a MILF",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "BDSM",
    pronounce: "as is",
    type: "INFORMAL",
    def: "A physical, psychological and usually sexual power-role-play with consensual participants.",
    def2: "bondage, domination, submission, masochism.",
    example: "(That one Rihanna song)",
  },
  {
    word: "SEXT",
    pronounce: "/sekst/",
    type: "INFORMAL",
    def: "send (someone) sexually explicit photographs or messages via mobile phone.",
    def2: "(none)",
    example: "Sexting, it's not sex it's the next best thing.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
];

export const CUSS_WORDS_APRIL = [
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },

  {
    word: "BUTT",
    pronounce: "/bət/",
    type: "COLLOQUIAL",
    def: "the buttocks or anus.",
    def2: "(anus)",
    example: "If you're good tonight, I'll let you put it in my butt.",
  },
  {
    word: "SHAG",
    pronounce: "/SHaɡ/",
    type: "VULGAR SLANG•BRITISH",
    def: "have sex with (someone).",
    def2: "an act of having sex.",
    example: "Shall we shag now? Or shag later?",
  },
  {
    word: "GASH",
    pronounce: "/ɡaSH/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example:
      "She's got a gash like the mariana trench, but she always lets me touch it!",
  },
  {
    word: "JUGS",
    pronounce: "/jəɡs/",
    type: "VULGAR SLANG",
    def: "a woman's breasts.",
    def2: "(none)",
    example: "Damn son, look at those jugs.",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "BANG",
    pronounce: "/baNG/",
    type: "VULGAR SLANG",
    def: "an act or instance of having sex.",
    def2: "(none)",
    example: "Let's go bang in the back of my Honda, baby.",
  },
  {
    word: "DIKE",
    pronounce: "/dīk/",
    type: "OFFENSIVE",
    def: "a lesbian.",
    def2: "(none)",
    example: "Bro, she must be a dike, she won't even let me get her number.",
  },
  {
    word: "FUCK",
    pronounce: "/fək/",
    type: "VULGAR SLANG",
    def: "have sex with (someone).",
    def2: "ruin or damage (something).",
    example: "Oh God YES! Fuck me! Fuck me harder!",
  },
  {
    word: "WOOD",
    pronounce: "/wo͝od/",
    type: "VULGAR SLANG•US",
    def: "have an erection",
    def2: "(none)",
    example: "I woke up with wood, man. Like I was pitching a tent.",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "SLIT",
    pronounce: "/slit/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example: "Nice slit, baby.",
  },
  {
    word: "DUMP",
    pronounce: "/dəmp/",
    type: "VULGAR SLANG",
    def: "an act of defecation.",
    def2: "(none)",
    example:
      "Bro, this cheesy gordida crunch is making me have to take a huge dump.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "TURD",
    pronounce: "/tərd/",
    type: "VULGAR SLANG",
    def: "a lump of excrement.",
    def2: "a person regarded as obnoxious or contemptible.",
    example:
      "There's a turd on the floor Josh, why the fuck is there a turd on the floor!?",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FROT",
    pronounce: "/fɹɒt/",
    type: "VULGAR SLANG",
    def: "A sexual act in which two males rub each other's penises",
    def2: "(none)",
    example: "Hey bro... want to frot?",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "TITS",
    pronounce: "/tits/ ",
    type: "VULGAR SLANG",
    def: "a woman's breasts or nipples.",
    def2: "(none)",
    example: "Excuse me mam, may I please play with your tits?",
  },
  {
    word: "COCK",
    pronounce: "/käk/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Nice cock, bro.",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "FART",
    pronounce: "/färt/",
    type: "INFORMAL",
    def: "emit gas from the anus.",
    def2: "waste time on silly or trivial things.",
    example: "Dude... did you just fart?",
  },
  {
    word: "POOP",
    pronounce: "/po͞op/",
    type: "INFORMAL",
    def: "excrement.",
    def2: "defecate.",
    example: "Don't go in there bro, someone smeard poop all over the stall.",
  },
  {
    word: "NIPS",
    pronounce: "/nips/",
    type: "INFORMAL",
    def: "a man's or woman's nipples.",
    def2: "(none)",
    example: "It's so cold in here my nips could cut glass.",
  },
  {
    word: "CRAP",
    pronounce: "/krap/",
    type: "VULGAR SLANG",
    def: "something of extremely poor quality.",
    def2: "excrement.",
    example: "This pasta tastes like crap.",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SIMP",
    pronounce: "/simp/",
    type: "DEROGATORY•INFORMAL",
    def: "a man that is too attentive and submissive to women",
    def2: "(none)",
    example:
      "Yeah, he totally simps for me. He watches my dog while I fuck his friend.",
  },
  {
    word: "ARSE",
    pronounce: "/ärs/",
    type: "VULGAR SLANG•BRITISH",
    def: "a person's buttocks or anus.",
    def2: "a stupid, irritating, or contemptible person.",
    example: "He's a pain in the arse, but he can really build a shed!",
  },
  {
    word: "WANK",
    pronounce: "/waNGk/",
    type: "VULGAR SLANG•BRITISH",
    def: "masturbate.",
    def2: "(none)",
    example: "Now if you'll all excuse me, I'm off to have a nice wank.",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
];

export const CUSS_WORDS_OCTOBER = [
  {
    word: "SLIT",
    pronounce: "/slit/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example: "Nice slit, baby.",
  },
  {
    word: "DUMP",
    pronounce: "/dəmp/",
    type: "VULGAR SLANG",
    def: "an act of defecation.",
    def2: "(none)",
    example:
      "Bro, this cheesy gordida crunch is making me have to take a huge dump.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "TURD",
    pronounce: "/tərd/",
    type: "VULGAR SLANG",
    def: "a lump of excrement.",
    def2: "a person regarded as obnoxious or contemptible.",
    example:
      "There's a turd on the floor Josh, why the fuck is there a turd on the floor!?",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FROT",
    pronounce: "/fɹɒt/",
    type: "VULGAR SLANG",
    def: "A sexual act in which two males rub each other's penises",
    def2: "(none)",
    example: "Hey bro... want to frot?",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "CLAM",
    pronounce: "/klam/",
    type: "VULGAR SLANG",
    def: "the female external genitals; the vulva, the vagina.",
    def2: "(none)",
    example:
      "Let's just say, he left me with a pearl in my clam. (girls don't ever say this)",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "MILF",
    pronounce: "/ˈmilf/",
    type: "INFORMAL",
    def: "a sexually attractive older woman, typically one who has children.",
    def2: "mother I'd like to fuck.",
    example: "I don't care how old she is, that bitch is a MILF",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "BDSM",
    pronounce: "as is",
    type: "INFORMAL",
    def: "A physical, psychological and usually sexual power-role-play with consensual participants.",
    def2: "bondage, domination, submission, masochism.",
    example: "(That one Rihanna song)",
  },
  {
    word: "SEXT",
    pronounce: "/sekst/",
    type: "INFORMAL",
    def: "send (someone) sexually explicit photographs or messages via mobile phone.",
    def2: "(none)",
    example: "Sexting, it's not sex it's the next best thing.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
  {
    word: "SEXT",
    pronounce: "/sekst/",
    type: "INFORMAL",
    def: "send (someone) sexually explicit photographs or messages via mobile phone.",
    def2: "(none)",
    example: "Sexting, it's not sex it's the next best thing.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "MILF",
    pronounce: "/ˈmilf/",
    type: "INFORMAL",
    def: "a sexually attractive older woman, typically one who has children.",
    def2: "mother I'd like to fuck.",
    example: "I don't care how old she is, that bitch is a MILF",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "BDSM",
    pronounce: "as is",
    type: "INFORMAL",
    def: "A physical, psychological and usually sexual power-role-play with consensual participants.",
    def2: "bondage, domination, submission, masochism.",
    example: "(That one Rihanna song)",
  },
];

export const CUSS_WORDS_JUNE = [
  {
    word: "SHIT",
    pronounce: "/SHit/",
    type: "VULGAR SLANG",
    def: "feces.",
    def2: "a contemptible or worthless person.",
    example: "Eat shit... you stupid piece of shit.",
  },
  {
    word: "PISS",
    pronounce: "/pis/",
    type: "VULGAR SLANG",
    def: "urinate.",
    def2: "(none)",
    example: "Bro! Wtf? Don't piss on my cat!",
  },
  {
    word: "CUNT",
    pronounce: "/kənt/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "a contemptible or worthless person.",
    example: "... and that's when I kicked her right in the cunt.",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "TITS",
    pronounce: "/tits/ ",
    type: "VULGAR SLANG",
    def: "a woman's breasts or nipples.",
    def2: "(none)",
    example: "Excuse me mam, may I please play with your tits?",
  },
  {
    word: "COCK",
    pronounce: "/käk/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Nice cock, bro.",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "FART",
    pronounce: "/färt/",
    type: "INFORMAL",
    def: "emit gas from the anus.",
    def2: "waste time on silly or trivial things.",
    example: "Dude... did you just fart?",
  },
  {
    word: "POOP",
    pronounce: "/po͞op/",
    type: "INFORMAL",
    def: "excrement.",
    def2: "defecate.",
    example: "Don't go in there bro, someone smeard poop all over the stall.",
  },
  {
    word: "NIPS",
    pronounce: "/nips/",
    type: "INFORMAL",
    def: "a man's or woman's nipples.",
    def2: "(none)",
    example: "It's so cold in here my nips could cut glass.",
  },
  {
    word: "CRAP",
    pronounce: "/krap/",
    type: "VULGAR SLANG",
    def: "something of extremely poor quality.",
    def2: "excrement.",
    example: "This pasta tastes like crap.",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SIMP",
    pronounce: "/simp/",
    type: "DEROGATORY•INFORMAL",
    def: "a man that is too attentive and submissive to women",
    def2: "(none)",
    example:
      "Yeah, he totally simps for me. He watches my dog while I fuck his friend.",
  },
  {
    word: "ARSE",
    pronounce: "/ärs/",
    type: "VULGAR SLANG•BRITISH",
    def: "a person's buttocks or anus.",
    def2: "a stupid, irritating, or contemptible person.",
    example: "He's a pain in the arse, but he can really build a shed!",
  },
  {
    word: "WANK",
    pronounce: "/waNGk/",
    type: "VULGAR SLANG•BRITISH",
    def: "masturbate.",
    def2: "(none)",
    example: "Now if you'll all excuse me, I'm off to have a nice wank.",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "WANK",
    pronounce: "/waNGk/",
    type: "VULGAR SLANG•BRITISH",
    def: "masturbate.",
    def2: "(none)",
    example: "Now if you'll all excuse me, I'm off to have a nice wank.",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "TURD",
    pronounce: "/tərd/",
    type: "VULGAR SLANG",
    def: "a lump of excrement.",
    def2: "a person regarded as obnoxious or contemptible.",
    example:
      "There's a turd on the floor Josh, why the fuck is there a turd on the floor!?",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FROT",
    pronounce: "/fɹɒt/",
    type: "VULGAR SLANG",
    def: "A sexual act in which two males rub each other's penises",
    def2: "(none)",
    example: "Hey bro... want to frot?",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "BUSH",
    pronounce: "/bo͝oSH/",
    type: "VULGAR SLANG",
    def: "a woman's pubic hair.",
    def2: "(none)",
    example: "A dick in the ass is worth two in the bush.",
  },
  {
    word: "PORN",
    pronounce: "/pôrn/",
    type: "INFORMAL",
    def: "pornography.",
    def2: "pornographic.",
    example:
      "I like my tacos with cilantro and porn - shit! Corn, I mean corn...",
  },
];

export const CUSS_WORDS_JULY = [
  {
    word: "FUCK",
    pronounce: "/fək/",
    type: "VULGAR SLANG",
    def: "have sex with (someone).",
    def2: "ruin or damage (something).",
    example: "Oh God YES! Fuck me! Fuck me harder!",
  },
  {
    word: "SHIT",
    pronounce: "/SHit/",
    type: "VULGAR SLANG",
    def: "feces.",
    def2: "a contemptible or worthless person.",
    example: "Eat shit... you stupid piece of shit.",
  },
  {
    word: "PISS",
    pronounce: "/pis/",
    type: "VULGAR SLANG",
    def: "urinate.",
    def2: "(none)",
    example: "Bro! Wtf? Don't piss on my cat!",
  },
  {
    word: "CUNT",
    pronounce: "/kənt/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "a contemptible or worthless person.",
    example: "... and that's when I kicked her right in the cunt.",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "TITS",
    pronounce: "/tits/ ",
    type: "VULGAR SLANG",
    def: "a woman's breasts or nipples.",
    def2: "(none)",
    example: "Excuse me mam, may I please play with your tits?",
  },
  {
    word: "COCK",
    pronounce: "/käk/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Nice cock, bro.",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "FART",
    pronounce: "/färt/",
    type: "INFORMAL",
    def: "emit gas from the anus.",
    def2: "waste time on silly or trivial things.",
    example: "Dude... did you just fart?",
  },
  {
    word: "POOP",
    pronounce: "/po͞op/",
    type: "INFORMAL",
    def: "excrement.",
    def2: "defecate.",
    example: "Don't go in there bro, someone smeard poop all over the stall.",
  },
  {
    word: "NIPS",
    pronounce: "/nips/",
    type: "INFORMAL",
    def: "a man's or woman's nipples.",
    def2: "(none)",
    example: "It's so cold in here my nips could cut glass.",
  },
  {
    word: "CRAP",
    pronounce: "/krap/",
    type: "VULGAR SLANG",
    def: "something of extremely poor quality.",
    def2: "excrement.",
    example: "This pasta tastes like crap.",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SIMP",
    pronounce: "/simp/",
    type: "DEROGATORY•INFORMAL",
    def: "a man that is too attentive and submissive to women",
    def2: "(none)",
    example:
      "Yeah, he totally simps for me. He watches my dog while I fuck his friend.",
  },
  {
    word: "ARSE",
    pronounce: "/ärs/",
    type: "VULGAR SLANG•BRITISH",
    def: "a person's buttocks or anus.",
    def2: "a stupid, irritating, or contemptible person.",
    example: "He's a pain in the arse, but he can really build a shed!",
  },
  {
    word: "WANK",
    pronounce: "/waNGk/",
    type: "VULGAR SLANG•BRITISH",
    def: "masturbate.",
    def2: "(none)",
    example: "Now if you'll all excuse me, I'm off to have a nice wank.",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },

  {
    word: "BUTT",
    pronounce: "/bət/",
    type: "COLLOQUIAL",
    def: "the buttocks or anus.",
    def2: "(anus)",
    example: "If you're good tonight, I'll let you put it in my butt.",
  },
  {
    word: "SHAG",
    pronounce: "/SHaɡ/",
    type: "VULGAR SLANG•BRITISH",
    def: "have sex with (someone).",
    def2: "an act of having sex.",
    example: "Shall we shag now? Or shag later?",
  },
  {
    word: "GASH",
    pronounce: "/ɡaSH/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example:
      "She's got a gash like the mariana trench, but she always lets me touch it!",
  },
  {
    word: "JUGS",
    pronounce: "/jəɡs/",
    type: "VULGAR SLANG",
    def: "a woman's breasts.",
    def2: "(none)",
    example: "Damn son, look at those jugs.",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "BANG",
    pronounce: "/baNG/",
    type: "VULGAR SLANG",
    def: "an act or instance of having sex.",
    def2: "(none)",
    example: "Let's go bang in the back of my Honda, baby.",
  },
  {
    word: "DIKE",
    pronounce: "/dīk/",
    type: "OFFENSIVE",
    def: "a lesbian.",
    def2: "(none)",
    example: "Bro, she must be a dike, she won't even let me get her number.",
  },
];

export const CUSS_WORDS_AUGUST = [
  {
    word: "PORN",
    pronounce: "/pôrn/",
    type: "INFORMAL",
    def: "pornography.",
    def2: "pornographic.",
    example:
      "I like my tacos with cilantro and porn - shit! Corn, I mean corn...",
  },
  {
    word: "JUGS",
    pronounce: "/jəɡs/",
    type: "VULGAR SLANG",
    def: "a woman's breasts.",
    def2: "(none)",
    example: "Damn son, look at those jugs.",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FUCK",
    pronounce: "/fək/",
    type: "VULGAR SLANG",
    def: "have sex with (someone).",
    def2: "ruin or damage (something).",
    example: "Oh God YES! Fuck me! Fuck me harder!",
  },
  {
    word: "FART",
    pronounce: "/färt/",
    type: "INFORMAL",
    def: "emit gas from the anus.",
    def2: "waste time on silly or trivial things.",
    example: "Dude... did you just fart?",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "SLIT",
    pronounce: "/slit/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example: "Nice slit, baby.",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "TITS",
    pronounce: "/tits/ ",
    type: "VULGAR SLANG",
    def: "a woman's breasts or nipples.",
    def2: "(none)",
    example: "Excuse me mam, may I please play with your tits?",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "ARSE",
    pronounce: "/ärs/",
    type: "VULGAR SLANG•BRITISH",
    def: "a person's buttocks or anus.",
    def2: "a stupid, irritating, or contemptible person.",
    example: "He's a pain in the arse, but he can really build a shed!",
  },
  {
    word: "PISS",
    pronounce: "/pis/",
    type: "VULGAR SLANG",
    def: "urinate.",
    def2: "(none)",
    example: "Bro! Wtf? Don't piss on my cat!",
  },
  {
    word: "CLAM",
    pronounce: "/klam/",
    type: "VULGAR SLANG",
    def: "the female external genitals; the vulva, the vagina.",
    def2: "(none)",
    example:
      "Let's just say, he left me with a pearl in my clam. (girls don't ever say this)",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "MILF",
    pronounce: "/ˈmilf/",
    type: "INFORMAL",
    def: "a sexually attractive older woman, typically one who has children.",
    def2: "mother I'd like to fuck.",
    example: "I don't care how old she is, that bitch is a MILF",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "BDSM",
    pronounce: "as is",
    type: "INFORMAL",
    def: "A physical, psychological and usually sexual power-role-play with consensual participants.",
    def2: "bondage, domination, submission, masochism.",
    example: "(That one Rihanna song)",
  },
  {
    word: "SEXT",
    pronounce: "/sekst/",
    type: "INFORMAL",
    def: "send (someone) sexually explicit photographs or messages via mobile phone.",
    def2: "(none)",
    example: "Sexting, it's not sex it's the next best thing.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
];

export const CUSS_WORDS_SEPTEMBER = [
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },

  {
    word: "BUTT",
    pronounce: "/bət/",
    type: "COLLOQUIAL",
    def: "the buttocks or anus.",
    def2: "(anus)",
    example: "If you're good tonight, I'll let you put it in my butt.",
  },
  {
    word: "SHAG",
    pronounce: "/SHaɡ/",
    type: "VULGAR SLANG•BRITISH",
    def: "have sex with (someone).",
    def2: "an act of having sex.",
    example: "Shall we shag now? Or shag later?",
  },
  {
    word: "GASH",
    pronounce: "/ɡaSH/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example:
      "She's got a gash like the mariana trench, but she always lets me touch it!",
  },
  {
    word: "JUGS",
    pronounce: "/jəɡs/",
    type: "VULGAR SLANG",
    def: "a woman's breasts.",
    def2: "(none)",
    example: "Damn son, look at those jugs.",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "BANG",
    pronounce: "/baNG/",
    type: "VULGAR SLANG",
    def: "an act or instance of having sex.",
    def2: "(none)",
    example: "Let's go bang in the back of my Honda, baby.",
  },
  {
    word: "DIKE",
    pronounce: "/dīk/",
    type: "OFFENSIVE",
    def: "a lesbian.",
    def2: "(none)",
    example: "Bro, she must be a dike, she won't even let me get her number.",
  },
  {
    word: "FUCK",
    pronounce: "/fək/",
    type: "VULGAR SLANG",
    def: "have sex with (someone).",
    def2: "ruin or damage (something).",
    example: "Oh God YES! Fuck me! Fuck me harder!",
  },
  {
    word: "WOOD",
    pronounce: "/wo͝od/",
    type: "VULGAR SLANG•US",
    def: "have an erection",
    def2: "(none)",
    example: "I woke up with wood, man. Like I was pitching a tent.",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "SLIT",
    pronounce: "/slit/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example: "Nice slit, baby.",
  },
  {
    word: "DUMP",
    pronounce: "/dəmp/",
    type: "VULGAR SLANG",
    def: "an act of defecation.",
    def2: "(none)",
    example:
      "Bro, this cheesy gordida crunch is making me have to take a huge dump.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "TURD",
    pronounce: "/tərd/",
    type: "VULGAR SLANG",
    def: "a lump of excrement.",
    def2: "a person regarded as obnoxious or contemptible.",
    example:
      "There's a turd on the floor Josh, why the fuck is there a turd on the floor!?",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FROT",
    pronounce: "/fɹɒt/",
    type: "VULGAR SLANG",
    def: "A sexual act in which two males rub each other's penises",
    def2: "(none)",
    example: "Hey bro... want to frot?",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "TITS",
    pronounce: "/tits/ ",
    type: "VULGAR SLANG",
    def: "a woman's breasts or nipples.",
    def2: "(none)",
    example: "Excuse me mam, may I please play with your tits?",
  },
  {
    word: "COCK",
    pronounce: "/käk/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Nice cock, bro.",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "FART",
    pronounce: "/färt/",
    type: "INFORMAL",
    def: "emit gas from the anus.",
    def2: "waste time on silly or trivial things.",
    example: "Dude... did you just fart?",
  },
  {
    word: "POOP",
    pronounce: "/po͞op/",
    type: "INFORMAL",
    def: "excrement.",
    def2: "defecate.",
    example: "Don't go in there bro, someone smeard poop all over the stall.",
  },
  {
    word: "NIPS",
    pronounce: "/nips/",
    type: "INFORMAL",
    def: "a man's or woman's nipples.",
    def2: "(none)",
    example: "It's so cold in here my nips could cut glass.",
  },
  {
    word: "CRAP",
    pronounce: "/krap/",
    type: "VULGAR SLANG",
    def: "something of extremely poor quality.",
    def2: "excrement.",
    example: "This pasta tastes like crap.",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SIMP",
    pronounce: "/simp/",
    type: "DEROGATORY•INFORMAL",
    def: "a man that is too attentive and submissive to women",
    def2: "(none)",
    example:
      "Yeah, he totally simps for me. He watches my dog while I fuck his friend.",
  },
  {
    word: "ARSE",
    pronounce: "/ärs/",
    type: "VULGAR SLANG•BRITISH",
    def: "a person's buttocks or anus.",
    def2: "a stupid, irritating, or contemptible person.",
    example: "He's a pain in the arse, but he can really build a shed!",
  },
  {
    word: "WANK",
    pronounce: "/waNGk/",
    type: "VULGAR SLANG•BRITISH",
    def: "masturbate.",
    def2: "(none)",
    example: "Now if you'll all excuse me, I'm off to have a nice wank.",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
];

export const CUSS_WORDS_MAY = [
  {
    word: "SLIT",
    pronounce: "/slit/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example: "Nice slit, baby.",
  },
  {
    word: "DUMP",
    pronounce: "/dəmp/",
    type: "VULGAR SLANG",
    def: "an act of defecation.",
    def2: "(none)",
    example:
      "Bro, this cheesy gordida crunch is making me have to take a huge dump.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "TURD",
    pronounce: "/tərd/",
    type: "VULGAR SLANG",
    def: "a lump of excrement.",
    def2: "a person regarded as obnoxious or contemptible.",
    example:
      "There's a turd on the floor Josh, why the fuck is there a turd on the floor!?",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FROT",
    pronounce: "/fɹɒt/",
    type: "VULGAR SLANG",
    def: "A sexual act in which two males rub each other's penises",
    def2: "(none)",
    example: "Hey bro... want to frot?",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "CLAM",
    pronounce: "/klam/",
    type: "VULGAR SLANG",
    def: "the female external genitals; the vulva, the vagina.",
    def2: "(none)",
    example:
      "Let's just say, he left me with a pearl in my clam. (girls don't ever say this)",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "MILF",
    pronounce: "/ˈmilf/",
    type: "INFORMAL",
    def: "a sexually attractive older woman, typically one who has children.",
    def2: "mother I'd like to fuck.",
    example: "I don't care how old she is, that bitch is a MILF",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "BDSM",
    pronounce: "as is",
    type: "INFORMAL",
    def: "A physical, psychological and usually sexual power-role-play with consensual participants.",
    def2: "bondage, domination, submission, masochism.",
    example: "(That one Rihanna song)",
  },
  {
    word: "SEXT",
    pronounce: "/sekst/",
    type: "INFORMAL",
    def: "send (someone) sexually explicit photographs or messages via mobile phone.",
    def2: "(none)",
    example: "Sexting, it's not sex it's the next best thing.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
  {
    word: "SEXT",
    pronounce: "/sekst/",
    type: "INFORMAL",
    def: "send (someone) sexually explicit photographs or messages via mobile phone.",
    def2: "(none)",
    example: "Sexting, it's not sex it's the next best thing.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "MILF",
    pronounce: "/ˈmilf/",
    type: "INFORMAL",
    def: "a sexually attractive older woman, typically one who has children.",
    def2: "mother I'd like to fuck.",
    example: "I don't care how old she is, that bitch is a MILF",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "BDSM",
    pronounce: "as is",
    type: "INFORMAL",
    def: "A physical, psychological and usually sexual power-role-play with consensual participants.",
    def2: "bondage, domination, submission, masochism.",
    example: "(That one Rihanna song)",
  },
];

export const CUSS_WORDS_NOVEMBER = [
  {
    word: "SHIT",
    pronounce: "/SHit/",
    type: "VULGAR SLANG",
    def: "feces.",
    def2: "a contemptible or worthless person.",
    example: "Eat shit... you stupid piece of shit.",
  },
  {
    word: "PISS",
    pronounce: "/pis/",
    type: "VULGAR SLANG",
    def: "urinate.",
    def2: "(none)",
    example: "Bro! Wtf? Don't piss on my cat!",
  },
  {
    word: "CUNT",
    pronounce: "/kənt/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "a contemptible or worthless person.",
    example: "... and that's when I kicked her right in the cunt.",
  },

  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "FUCK",
    pronounce: "/fək/",
    type: "VULGAR SLANG",
    def: "have sex with (someone).",
    def2: "ruin or damage (something).",
    example: "Oh God YES! Fuck me! Fuck me harder!",
  },
  {
    word: "TITS",
    pronounce: "/tits/ ",
    type: "VULGAR SLANG",
    def: "a woman's breasts or nipples.",
    def2: "(none)",
    example: "Excuse me mam, may I please play with your tits?",
  },
  {
    word: "COCK",
    pronounce: "/käk/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Nice cock, bro.",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "FART",
    pronounce: "/färt/",
    type: "INFORMAL",
    def: "emit gas from the anus.",
    def2: "waste time on silly or trivial things.",
    example: "Dude... did you just fart?",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "POOP",
    pronounce: "/po͞op/",
    type: "INFORMAL",
    def: "excrement.",
    def2: "defecate.",
    example: "Don't go in there bro, someone smeard poop all over the stall.",
  },
  {
    word: "NIPS",
    pronounce: "/nips/",
    type: "INFORMAL",
    def: "a man's or woman's nipples.",
    def2: "(none)",
    example: "It's so cold in here my nips could cut glass.",
  },
  {
    word: "HELL",
    pronounce: "/hel/",
    type: "COLLOQUIAL",
    def: "a state or place of great suffering; an unbearable experience.",
    def2: "a place regarded in various religions as a spiritual realm of evil and suffering.",
    example: "I'll see you in hell!",
  },
  {
    word: "THOT",
    pronounce: "/THät/",
    type: "DEROGATORY•INFORMAL",
    def: "a woman who has many casual sexual encounters or relationships.",
    def2: "(none)",
    example: "Bitch be a thot yo. Up on errrryone's dick",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SIMP",
    pronounce: "/simp/",
    type: "DEROGATORY•INFORMAL",
    def: "a man that is too attentive and submissive to women",
    def2: "(none)",
    example:
      "Yeah, he totally simps for me. He watches my dog while I fuck his friend.",
  },
  {
    word: "CRAP",
    pronounce: "/krap/",
    type: "VULGAR SLANG",
    def: "something of extremely poor quality.",
    def2: "excrement.",
    example: "This pasta tastes like crap.",
  },
  {
    word: "ARSE",
    pronounce: "/ärs/",
    type: "VULGAR SLANG•BRITISH",
    def: "a person's buttocks or anus.",
    def2: "a stupid, irritating, or contemptible person.",
    example: "He's a pain in the arse, but he can really build a shed!",
  },
  {
    word: "WANK",
    pronounce: "/waNGk/",
    type: "VULGAR SLANG•BRITISH",
    def: "masturbate.",
    def2: "(none)",
    example: "Now if you'll all excuse me, I'm off to have a nice wank.",
  },
  {
    word: "KNOB",
    pronounce: "/näb/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Can't wait to get home and polish my knob!",
  },
  {
    word: "CUCK",
    pronounce: "/kək/",
    type: "DEROGATORY•INFORMAL",
    def: "a weak or servile man.",
    def2: "a man whose wife is sexually unfaithful; a cuckold.",
    example:
      "I hate to cuck you baby, but I just can't get enough of that dick!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },

  {
    word: "BUTT",
    pronounce: "/bət/",
    type: "COLLOQUIAL",
    def: "the buttocks or anus.",
    def2: "(anus)",
    example: "If you're good tonight, I'll let you put it in my butt.",
  },
  {
    word: "SHAG",
    pronounce: "/SHaɡ/",
    type: "VULGAR SLANG•BRITISH",
    def: "have sex with (someone).",
    def2: "an act of having sex.",
    example: "Shall we shag now? Or shag later?",
  },
  {
    word: "GASH",
    pronounce: "/ɡaSH/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example:
      "She's got a gash like the mariana trench, but she always lets me touch it!",
  },
  {
    word: "JUGS",
    pronounce: "/jəɡs/",
    type: "VULGAR SLANG",
    def: "a woman's breasts.",
    def2: "(none)",
    example: "Damn son, look at those jugs.",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "BANG",
    pronounce: "/baNG/",
    type: "VULGAR SLANG",
    def: "an act or instance of having sex.",
    def2: "(none)",
    example: "Let's go bang in the back of my Honda, baby.",
  },
  {
    word: "DIKE",
    pronounce: "/dīk/",
    type: "OFFENSIVE",
    def: "a lesbian.",
    def2: "(none)",
    example: "Bro, she must be a dike, she won't even let me get her number.",
  },
];

export const CUSS_WORDS_DECEMBER = [
  {
    word: "SLIT",
    pronounce: "/slit/",
    type: "VULGAR SLANG",
    def: "the vulva.",
    def2: "(none)",
    example: "Nice slit, baby.",
  },
  {
    word: "DUMP",
    pronounce: "/dəmp/",
    type: "VULGAR SLANG",
    def: "an act of defecation.",
    def2: "(none)",
    example:
      "Bro, this cheesy gordida crunch is making me have to take a huge dump.",
  },
  {
    word: "CLIT",
    pronounce: "/klit/",
    type: "VULGAR SLANG",
    def: "(not found)",
    def2: "(not found)",
    example: "(not found)",
  },
  {
    word: "HUMP",
    pronounce: "/həmp/",
    type: "VULGAR SLANG",
    def: "have sex with.",
    def2: "(none)",
    example: "He must be Mr. Right, my dog just can't stop humping his leg!",
  },
  {
    word: "TURD",
    pronounce: "/tərd/",
    type: "VULGAR SLANG",
    def: "a lump of excrement.",
    def2: "a person regarded as obnoxious or contemptible.",
    example:
      "There's a turd on the floor Josh, why the fuck is there a turd on the floor!?",
  },
  {
    word: "ANAL",
    pronounce: "/ˈānl/",
    type: "VULGAR SLANG",
    def: "sexual activity involving penetration of the anus.",
    def2: "(none)",
    example:
      "My boyfiend and I tried anal the other night, he said next time we need to use a smaller dildo.",
  },
  {
    word: "FROT",
    pronounce: "/fɹɒt/",
    type: "VULGAR SLANG",
    def: "A sexual act in which two males rub each other's penises",
    def2: "(none)",
    example: "Hey bro... want to frot?",
  },
  {
    word: "GIMP",
    pronounce: "/ɡimp/",
    type: "DEROGATORY•INFORMAL",
    def: "a sexual fetishist who likes to be dominated.",
    def2: "dresses in a leather or rubber body suit with mask, zips, and chains.",
    example: "Ah shit. I left my gimp suit at the petting zoo last week.",
  },
  {
    word: "PIMP",
    pronounce: "/pimp/",
    type: "COLLOQUIAL",
    def: "a man who controls prostitutes and arranges clients for them, taking part of their earnings in return.",
    def2: "(none)",
    example:
      "I don't know what your heard about me, but I'm a motherfucking P.I.M.P",
  },
  {
    word: "BOOB",
    pronounce: "/bo͞ob/",
    type: "COLLOQUIAL",
    def: "a woman's breast.",
    def2: "a foolish or stupid person.",
    example: "We totally had sex, I touched her boob!",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "BUSH",
    pronounce: "/bo͝oSH/",
    type: "VULGAR SLANG",
    def: "a woman's pubic hair.",
    def2: "(none)",
    example: "A dick in the ass is worth two in the bush.",
  },
  {
    word: "PORN",
    pronounce: "/pôrn/",
    type: "INFORMAL",
    def: "pornography.",
    def2: "pornographic.",
    example:
      "I like my tacos with cilantro and porn - shit! Corn, I mean corn...",
  },
  {
    word: "CLAM",
    pronounce: "/klam/",
    type: "VULGAR SLANG",
    def: "the female external genitals; the vulva, the vagina.",
    def2: "(none)",
    example:
      "Let's just say, he left me with a pearl in my clam. (girls don't ever say this)",
  },
  {
    word: "MILF",
    pronounce: "/ˈmilf/",
    type: "INFORMAL",
    def: "a sexually attractive older woman, typically one who has children.",
    def2: "mother I'd like to fuck.",
    example: "I don't care how old she is, that bitch is a MILF",
  },
  {
    word: "BDSM",
    pronounce: "as is",
    type: "INFORMAL",
    def: "A physical, psychological and usually sexual power-role-play with consensual participants.",
    def2: "bondage, domination, submission, masochism.",
    example: "(That one Rihanna song)",
  },
  {
    word: "SEXT",
    pronounce: "/sekst/",
    type: "INFORMAL",
    def: "send (someone) sexually explicit photographs or messages via mobile phone.",
    def2: "(none)",
    example: "Sexting, it's not sex it's the next best thing.",
  },
  {
    word: "WOOD",
    pronounce: "/wo͝od/",
    type: "VULGAR SLANG•US",
    def: "have an erection",
    def2: "(none)",
    example: "I woke up with wood, man. Like I was pitching a tent.",
  },
  {
    word: "SOAK",
    pronounce: "/sōk/",
    type: "VULGAR SLANG•US",
    def: "penetrative sex without the movement and hip thrusting.",
    def2: "(none)",
    example: "We can soak, baby. It's not like it's really sex anyway.",
  },
  {
    word: "MUFF",
    pronounce: "/məf/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "(none)",
    example: "She's serving up a platter of succulent tits and muff.",
  },
  {
    word: "NUTS",
    pronounce: "/nəts/",
    type: "COLLOQUIAL",
    def: "a man's genitalia.",
    def2: "insane.",
    example:
      "Dr. Evil, I knew that you were crazy... but now I can see your nuts!",
  },
  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "DICK",
    pronounce: "/dik/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "an arrogant contemptible person.",
    example: "Wow... what a dick...",
  },
  {
    word: "TWAT",
    pronounce: "/twät/",
    type: "VULGAR SLANG",
    def: "a stupid or obnoxious person.",
    def2: "a woman's genitals.",
    example: "Sit down Billy, you're being a little twat.",
  },
  {
    word: "COCK",
    pronounce: "/käk/ ",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "Nice cock, bro.",
  },
  {
    word: "DAMN",
    pronounce: "/dam/",
    type: "COLLOQUIAL",
    def: "expressing anger, surprise, or frustration.",
    def2: "condemn, especially by the public expression of disapproval.",
    example: "Damn you! Damn you all to hell!",
  },
  {
    word: "SLUT",
    pronounce: "/slət/",
    type: "OFFENSIVE",
    def: "a woman who has many casual sexual partners.",
    def2: "(none)",
    example: "Dwight! You ignorant slut!",
  },
  {
    word: "DONG",
    pronounce: "/dôNG/",
    type: "VULGAR SLANG",
    def: "a penis.",
    def2: "(none)",
    example: "No way I would touch it, he had this weird shit on his dong.",
  },
  {
    word: "ANUS",
    pronounce: "/ˈānəs/",
    type: "COLLOQUIAL",
    def: "the opening at the end of the alimentary canal through which solid waste matter leaves the body.",
    def2: "(none)",
    example: "They hate us... because they anus.",
  },
  {
    word: "BUSH",
    pronounce: "/bo͝oSH/",
    type: "VULGAR SLANG",
    def: "a woman's pubic hair.",
    def2: "(none)",
    example: "A dick in the ass is worth two in the bush.",
  },
  {
    word: "CUNT",
    pronounce: "/kənt/",
    type: "VULGAR SLANG",
    def: "a woman's genitals.",
    def2: "a contemptible or worthless person.",
    example: "... and that's when I kicked her right in the cunt.",
  },

  {
    word: "JIZZ",
    pronounce: "/jiz/ ",
    type: "VULGAR SLANG",
    def: "semen.",
    def2: "to ejaculate.",
    example: "Wow, there is jizz all over this couch.",
  },
  {
    word: "FUCK",
    pronounce: "/fək/",
    type: "VULGAR SLANG",
    def: "have sex with (someone).",
    def2: "ruin or damage (something).",
    example: "Oh God YES! Fuck me! Fuck me harder!",
  },
  {
    word: "CRAP",
    pronounce: "/krap/",
    type: "VULGAR SLANG",
    def: "something of extremely poor quality.",
    def2: "excrement.",
    example: "This pasta tastes like crap.",
  },
];
